//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRIPCION_ESTUDIANTES
    {
        public string CARNET { get; set; }
        public System.DateTime FECHA_ADICION { get; set; }
    
        public virtual ESTUDIANTES ESTUDIANTES { get; set; }
    }
}
